"""
Researcher dataset catalog routes.

Provides a curated static catalog of datasets used by AquaGuardians.
"""
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db import CommunityReport, get_db

router = APIRouter()

DATASET_CATALOG = [
    {
        "id": "imd-gridded-rainfall",
        "name": "IMD Gridded Rainfall (Daily)",
        "category": "rainfall",
        "provider": "India Meteorological Department (IMD), Pune",
        "description": "High-resolution daily gridded rainfall over India. Primary rainfall input for flood prediction.",
        "time_range": "1901-present",
        "spatial_resolution": "0.25 deg x 0.25 deg (~25 km)",
        "temporal_resolution": "Daily",
        "format": "NetCDF / GRD",
        "size": "~2 GB archive",
        "license": "Government of India research use (registration required)",
        "access_url": "https://cdsp.imdpune.gov.in/",
        "access_method": "Register -> login -> download via Climate Data Services Portal",
        "used_in": ["flood_prediction", "rainfall_anomaly", "antecedent_precipitation_index"],
        "tags": ["rainfall", "meteorological", "gridded", "india"],
    },
    {
        "id": "imd-subdivision-rainfall",
        "name": "IMD Sub-division Monthly Rainfall",
        "category": "rainfall",
        "provider": "India Meteorological Department via data.gov.in",
        "description": "Monthly rainfall aggregated by meteorological sub-divisions for regional trend analysis.",
        "time_range": "1901-present",
        "spatial_resolution": "Sub-division",
        "temporal_resolution": "Monthly",
        "format": "CSV / Excel",
        "size": "~5 MB",
        "license": "NDSAP open data",
        "access_url": "https://www.data.gov.in/catalog/rainfall-india",
        "access_method": "Direct download",
        "used_in": ["trend_analysis", "monsoon_monitoring"],
        "tags": ["rainfall", "monthly", "sub-division", "open-data"],
    },
    {
        "id": "kaggle-rainfall-india",
        "name": "Rainfall in India (Kaggle)",
        "category": "rainfall",
        "provider": "Kaggle community",
        "description": "Pre-cleaned district-wise monthly rainfall data for rapid prototyping.",
        "time_range": "1901-2015",
        "spatial_resolution": "District",
        "temporal_resolution": "Monthly",
        "format": "CSV",
        "size": "~15 MB",
        "license": "CC0",
        "access_url": "https://www.kaggle.com/datasets/rajanand/rainfall-in-india",
        "access_method": "Kaggle download (account required)",
        "used_in": ["flood_prediction", "feature_engineering"],
        "tags": ["rainfall", "district", "csv"],
    },
    {
        "id": "era5-reanalysis",
        "name": "ERA5 Reanalysis",
        "category": "rainfall",
        "provider": "ECMWF / Copernicus",
        "description": "Global hourly reanalysis with rainfall, temperature, humidity, and soil moisture variables.",
        "time_range": "1940-present",
        "spatial_resolution": "0.25 deg",
        "temporal_resolution": "Hourly",
        "format": "NetCDF / GRIB",
        "size": "Request based",
        "license": "Copernicus free license",
        "access_url": "https://cds.climate.copernicus.eu/",
        "access_method": "Register -> CDS API / web request",
        "used_in": ["flood_prediction", "temperature_features", "soil_moisture"],
        "tags": ["reanalysis", "global", "hourly"],
    },
    {
        "id": "india-wris",
        "name": "India-WRIS",
        "category": "hydrology",
        "provider": "CWC + ISRO/NRSC",
        "description": "National hydrology portal with gauge station water level and discharge data.",
        "time_range": "Varies by station",
        "spatial_resolution": "Gauge station",
        "temporal_resolution": "Daily",
        "format": "Web / CSV export",
        "size": "Variable",
        "license": "Government of India",
        "access_url": "https://indiawris.gov.in/",
        "access_method": "Register -> Hydro Observations -> station export",
        "used_in": ["river_level_features", "discharge_prediction"],
        "tags": ["discharge", "water-level", "stations"],
        "notes": "Some major basins are restricted and require formal request.",
    },
    {
        "id": "guardian-discharge",
        "name": "GUARDIAN Discharge Dataset",
        "category": "hydrology",
        "provider": "IIT Bombay",
        "description": "Sub-daily discharge for CWC stations from 2020 onward for real-time hydrology analysis.",
        "time_range": "2020-present",
        "spatial_resolution": "Gauge station",
        "temporal_resolution": "Sub-daily",
        "format": "CSV / NetCDF",
        "size": "~500 MB",
        "license": "CC-BY 4.0",
        "access_url": "https://doi.org/10.1038/s41597-024-03923-8",
        "access_method": "Supplementary dataset download",
        "used_in": ["real_time_river_monitoring", "discharge_features"],
        "tags": ["discharge", "real-time", "telemetry"],
    },
    {
        "id": "cwc-flood-forecast",
        "name": "CWC Advisory Flood Forecast Portal",
        "category": "hydrology",
        "provider": "Central Water Commission",
        "description": "Real-time and 7-day forecasted water levels across monitored stations.",
        "time_range": "Real-time + 7-day",
        "spatial_resolution": "Gauge station",
        "temporal_resolution": "3-hourly updates",
        "format": "Web",
        "size": "N/A",
        "license": "Public access",
        "access_url": "https://ffs.india-water.gov.in/",
        "access_method": "Portal access, scraping needed for programmatic usage",
        "used_in": ["real_time_alerts", "model_validation"],
        "tags": ["forecast", "real-time", "flood-warning"],
    },
    {
        "id": "ifi-impacts-v3",
        "name": "IFI-Impacts v3",
        "category": "flood_events",
        "provider": "HydroSense Lab, IIT Delhi",
        "description": "Comprehensive India flood event inventory with impacts, locations, and timelines.",
        "time_range": "1967-2023",
        "spatial_resolution": "District",
        "temporal_resolution": "Event based",
        "format": "GeoJSON / SHP / CSV",
        "size": "~50 MB",
        "license": "CC-BY 4.0",
        "access_url": "https://zenodo.org/records/11275211",
        "access_method": "Direct download",
        "used_in": ["flood_prediction_labels", "historical_analysis", "loss_estimation"],
        "tags": ["flood-events", "inventory", "labels"],
    },
    {
        "id": "indofloods",
        "name": "INDOFLOODS",
        "category": "flood_events",
        "provider": "HydroSense Lab, IIT Delhi",
        "description": "Event dataset from observed streamflow and flood thresholds across Indian stations.",
        "time_range": "1959-2020",
        "spatial_resolution": "Gauge station",
        "temporal_resolution": "Event based",
        "format": "CSV + SHP",
        "size": "~200 MB",
        "license": "CC-BY 4.0",
        "access_url": "https://zenodo.org/records/14584655",
        "access_method": "Zenodo download, contact authors for restricted basin coverage",
        "used_in": ["flood_prediction", "catchment_analysis", "model_validation"],
        "tags": ["flood-events", "discharge", "catchment"],
        "notes": "Public version excludes some restricted basins.",
    },
    {
        "id": "emdat",
        "name": "EM-DAT Disaster Database",
        "category": "flood_events",
        "provider": "CRED",
        "description": "Global disaster impact records including flood damage and affected population.",
        "time_range": "1900-present",
        "spatial_resolution": "Country/sub-national",
        "temporal_resolution": "Event based",
        "format": "Excel / CSV",
        "size": "~10 MB (India flood subset)",
        "license": "Research use (registration required)",
        "access_url": "https://www.emdat.be/",
        "access_method": "Register -> query export",
        "used_in": ["loss_estimation", "ppp_model", "damage_validation"],
        "tags": ["disaster", "economic-damage", "global"],
    },
    {
        "id": "nmcg-lidar",
        "name": "NMCG LiDAR DEM (Ganga Corridor)",
        "category": "terrain",
        "provider": "NMCG / Survey of India",
        "description": "High-resolution LiDAR DEM used for terrain-aware flood analysis in covered zones.",
        "time_range": "Static",
        "spatial_resolution": "0.5-1m",
        "format": "GeoTIFF",
        "size": "~1.7 GB per zone",
        "license": "Restricted distribution",
        "access_url": "Provided via project/hackathon package",
        "access_method": "Local file system",
        "used_in": ["elevation_features", "flood_zone_mapping", "3d_terrain", "report_verification"],
        "tags": ["lidar", "dem", "high-resolution"],
    },
    {
        "id": "copernicus-dem",
        "name": "Copernicus DEM (GLO-30)",
        "category": "terrain",
        "provider": "ESA / Copernicus",
        "description": "Global 30m DEM for regions outside local LiDAR coverage.",
        "time_range": "Static",
        "spatial_resolution": "30m",
        "format": "GeoTIFF",
        "size": "~50 MB per tile",
        "license": "Open",
        "access_url": "https://panda.copernicus.eu/panda",
        "access_method": "Portal / cloud download",
        "used_in": ["elevation_features", "slope_gradient", "drainage_analysis"],
        "tags": ["dem", "global", "30m"],
    },
    {
        "id": "srtm-dem",
        "name": "SRTM DEM v3",
        "category": "terrain",
        "provider": "NASA / USGS",
        "description": "Widely used global elevation baseline data.",
        "time_range": "Static",
        "spatial_resolution": "30m",
        "format": "GeoTIFF / HGT",
        "size": "~25 MB per tile",
        "license": "Public domain",
        "access_url": "https://earthexplorer.usgs.gov/",
        "access_method": "USGS EarthExplorer",
        "used_in": ["elevation_features", "fallback_dem"],
        "tags": ["dem", "global", "nasa"],
    },
    {
        "id": "google-open-buildings",
        "name": "Google Open Buildings V3",
        "category": "exposure",
        "provider": "Google Research",
        "description": "Large-scale building footprint data for exposure and asset estimation.",
        "time_range": "2023 imagery",
        "spatial_resolution": "Building polygon",
        "format": "CSV / GeoJSON",
        "size": "~5 GB India subset",
        "license": "CC-BY 4.0",
        "access_url": "https://sites.research.google/open-buildings/",
        "access_method": "Download by region",
        "used_in": ["exposure_estimation", "ppp_model", "building_count"],
        "tags": ["buildings", "footprints", "exposure"],
    },
    {
        "id": "worldpop",
        "name": "WorldPop Population Density",
        "category": "exposure",
        "provider": "WorldPop",
        "description": "High-resolution gridded population for impact and evacuation analysis.",
        "time_range": "2000-2020",
        "spatial_resolution": "100m",
        "temporal_resolution": "Annual",
        "format": "GeoTIFF",
        "size": "~200 MB/year",
        "license": "CC-BY 4.0",
        "access_url": "https://www.worldpop.org/geodata/listing?id=69",
        "access_method": "Direct download",
        "used_in": ["population_exposure", "ppp_model", "evacuation_planning"],
        "tags": ["population", "gridded", "100m"],
    },
    {
        "id": "jrc-damage-curves",
        "name": "JRC Flood Depth-Damage Functions",
        "category": "vulnerability",
        "provider": "European Commission JRC",
        "description": "Standard depth-damage references across sectors for flood loss estimation.",
        "time_range": "Static",
        "spatial_resolution": "Country-level",
        "temporal_resolution": "N/A",
        "format": "Excel / PDF",
        "size": "~5 MB",
        "license": "Open",
        "access_url": "https://publications.jrc.ec.europa.eu/repository/handle/JRC105688",
        "access_method": "Direct download",
        "used_in": ["loss_estimation", "ppp_model", "vulnerability_assessment"],
        "tags": ["damage-curves", "vulnerability", "loss"],
    },
    {
        "id": "osm-india",
        "name": "OpenStreetMap India Extract",
        "category": "exposure",
        "provider": "OpenStreetMap / Geofabrik",
        "description": "Infrastructure vector data including roads, bridges, waterways, and utilities.",
        "time_range": "Continuously updated",
        "spatial_resolution": "Feature-level vector",
        "temporal_resolution": "Daily updates",
        "format": "PBF / SHP / GeoJSON",
        "size": "~1.5 GB PBF",
        "license": "ODbL",
        "access_url": "https://download.geofabrik.de/asia/india.html",
        "access_method": "Direct download",
        "used_in": ["infrastructure_exposure", "evacuation_routing", "road_network"],
        "tags": ["roads", "infrastructure", "vector"],
    },
    {
        "id": "bhuvan-lulc",
        "name": "Bhuvan Land Use / Land Cover",
        "category": "exposure",
        "provider": "ISRO / NRSC",
        "description": "India land use maps for asset typing and exposure classification.",
        "time_range": "Multi-temporal",
        "spatial_resolution": "~56m",
        "format": "GeoTIFF / Web",
        "size": "Variable",
        "license": "Research use",
        "access_url": "https://bhuvan.nrsc.gov.in/",
        "access_method": "Portal registration + download",
        "used_in": ["land_use_features", "exposure_classification", "crop_damage"],
        "tags": ["land-use", "isro", "satellite"],
    },
]

DATASET_CATEGORIES = {
    "rainfall": {
        "label": "Rainfall & Meteorological",
        "icon": "cloud-rain",
        "color": "blue",
    },
    "hydrology": {
        "label": "River Discharge & Hydrology",
        "icon": "waves",
        "color": "cyan",
    },
    "flood_events": {
        "label": "Flood Event Inventories",
        "icon": "alert-triangle",
        "color": "red",
    },
    "terrain": {
        "label": "Elevation & Terrain",
        "icon": "mountain",
        "color": "amber",
    },
    "exposure": {
        "label": "Exposure & Socioeconomic",
        "icon": "building",
        "color": "green",
    },
    "vulnerability": {
        "label": "Vulnerability & Damage",
        "icon": "shield-alert",
        "color": "orange",
    },
}


@router.get("/datasets")
async def get_datasets(category: Optional[str] = None):
    """Return all datasets, optionally filtered by category key."""
    datasets = DATASET_CATALOG
    if category:
        datasets = [item for item in DATASET_CATALOG if item["category"] == category]
    return {"datasets": datasets, "categories": DATASET_CATEGORIES}


@router.get("/datasets/{dataset_id}")
async def get_dataset_detail(dataset_id: str):
    """Return one dataset by id."""
    for dataset in DATASET_CATALOG:
        if dataset["id"] == dataset_id:
            return dataset
    raise HTTPException(status_code=404, detail="Dataset not found")


@router.get("/researcher-stats")
async def get_researcher_stats(db: AsyncSession = Depends(get_db)):
    """High-level stats for the researcher dashboard home page."""
    total_reports = 0
    try:
        result = await db.execute(select(func.count(CommunityReport.id)))
        total_reports = int(result.scalar() or 0)
    except Exception:
        total_reports = 0

    return {
        "total_datasets": len(DATASET_CATALOG),
        "total_models": 6,
        "active_models": 2,
        "api_endpoints": 20,
        "total_reports": total_reports,
        "platform_version": "1.0.0",
        "data_coverage": "Ganga Basin (UP, Bihar, Uttarakhand, West Bengal)",
        "temporal_coverage": "1967-2026",
    }
